# Site configuration
title: "MrSiejas"
description: "Cloud meets AI"
url: "https://mrsiejas.github.io"
baseurl: ""

# Theme
remote_theme: daviddarnes/alembic@main

# Author details for CV
author:
  name: "Blazej Siejek"
  email: "blazej.siejek@gmail.com"
  linkedin: "https://www.linkedin.com/in/blazejsiejek/"
  github: "mrsiejas"

# Navigation
navigation_header:
  - title: Home
    url: /
  - title: CV
    url: /cv/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Collections for organizing content
collections:
  experiences:
    output: false
  education:
    output: false

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Blog pagination (simple version for GitHub Pages)
paginate: 5
paginate_path: "/blog/page:num/"