# Site configuration
title: "MrSiejas"
description: "Cloud meets AI"
url: "https://mrsiejas.github.io"
baseurl: ""

# Theme
remote_theme: daviddarnes/alembic@main

# Author details for CV
author:
  name: "Blazej Siejek"
  email: "blazej.siejek@gmail.com"
  linkedin: "https://www.linkedin.com/in/blazejsiejek/"
  github: "mrsiejas"

# Navigation
navigation_header:
  - title: Home
    url: /
  - title: CV
    url: /cv/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Collections for organizing content
collections:
  experiences:
    output: false
  education:
    output: false

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

# Blog pagination (using paginate-v2 which works better with GitHub Pages)
pagination:
  enabled: true
  per_page: 5
  permalink: '/blog/page:num/'
  sort_reverse: true