# Site configuration
title: "MrSiejas"
description: "Cloud meets AI"
url: "https://mrsiejas.github.io"
baseurl: ""

# Development server settings
port: 4001

# Theme
theme: alembic-jekyll-theme

# Author details for CV
author:
  name: "Blazej Siejek"
  linkedin: "https://www.linkedin.com/in/blazejsiejek/"
  github: "mrsiejas"

# Navigation
navigation_header:
  - title: Home
    url: /
  - title: CV
    url: /cv/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Footer navigation (empty to remove the footer links)
navigation_footer:
  - title: Contact
    url: /contact/
  - title: LinkedIn
    url: https://www.linkedin.com/in/blazejsiejek/

# Collections for organizing content
collections:
  experiences:
    output: false
  education:
    output: false

# Plugins (minimal set)
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Remove all pagination for now